[package]
edition = "2024"
name = "functions"
version = "0.1.0"

[dependencies]
tokio = {version = "1", features = ["rt", "macros", "rt-multi-thread"]}
warp = {version = "0.4", features = ["server"]}
